mkdocs.yml
=> update the docs 

mkdocs.yml
add [joins(outer join/natural join) and datetimes(extract/date-add/date-sub/to-date/unix-timestamp/from-unixtime/utc-timestamp] path
=> add joins and datetimes path

.github/workflows/lint.yml
遇到 github 自身问题
ad-a396-bb0cd594069d.sh: line 403: unexpected EOF while looking for matching `''
=> fix: remove echo github bugfix

.github/workflows/pre-cd.yml
=> fix: remove cd git add

docs/MatrixOne/Develop/import-data/insert-data.md
=> [Doc] Update `Customer` to `Customers`

mkdocs.yml
=> fix: update edit_url

requirements.txt
=> fix: update requirements mkdocs 8.2.8

docs/MatrixOne/Develop/connect-mo/python-connect-to-matrixone.md, docs/MatrixOne/Test/mo-tester.md
- Synchronizing Chinese Documents：Connecting to MatrixOne with Python
- fix broken link bug : mo-tester
issue #
=> Synchronizing Chinese Documents

docs/MatrixOne/Develop/import-data/bulk-load/load-jsonline.md
The link of json file failed，this PR will fix this bug
issue # https://github.com/matrixorigin/matrixorigin.io/issues/204
=> fix the broken links of jsonline doc

docs/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md
The translation of *8select** is incorrect
this PR will fix this bug
issue #138
=> update mybatis translation

docs/MatrixOne/Tutorial/develop-java-crud-demo.md
Description error in Java CURD documentation
This PR will fix these bugs
issue #130
=> fix_bugs_in_issue_130

docs/MatrixOne/Tutorial/develop-java-crud-demo.md
=> Synchronize Chinese documents  of java crud

docs/MatrixOne/Tutorial/springboot-hibernate-crud-demo.md, docs/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md, mkdocs.yml
=> Synchronize Chinese documents:sprigngboot crud demos

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/explicit-transaction.md, docs/MatrixOne/Develop/import-data/bulk-load/load-s3.md, docs/MatrixOne/Reference/System-tables.md
=> sync chinese docs:load s3/system_table/explicit-transaction

docs/MatrixOne/Reference/Data-Types/data-types.md
issue #
https://github.com/matrixorigin/matrixorigin.io/issues/173
=> fix bugs in io.cn issue 173

docs/MatrixOne/Develop/import-data/bulk-load/load-s3.md
=> fix load s3 statement error

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
=> add examples to load data doc

docs/MatrixOne/Reference/SQL-Reference/Database-Administration-Statements/create-user.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/100
=> fix bugs in io.cn issue 100

docs/MatrixOne/Reference/SQL-Reference/Database-Administration-Statements/set-role.md, docs/MatrixOne/Test/performance-testing/TPCH-test-with-matrixone.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/102
=> fix bugs in io.cn issue 102

scripts/genZhlintConfig.js
issue #197
修改 `zhlint` 配置，删除对标点的校验，仅校验空格：
+ 全角、半角符号之间的空格；
+ 删除尾部空格。
=> fix(lint): process only spaces

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/explicit-transaction.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/208
=> update docs in io issue 208

docs/MatrixOne/Troubleshooting/audit.md
issue #
https://github.com/matrixorigin/matrixorigin.io/issues/263
=> update docs in io issue 263

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/explicit-transaction.md, docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/implicit-transaction.md, docs/README.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/209
=> update docs in io issue 209

docs/MatrixOne/Deploy/0.7-deploy-MatrixOne-cluster.md
=> update 0.7 deploy mo cluster doc

docs/MatrixOne/Develop/import-data/bulk-load/0.7-bulk-load-overview.md, docs/MatrixOne/Develop/import-data/bulk-load/0.7-load-s3.md, docs/MatrixOne/Get-Started/basic-sql.md, docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/0.7-load-data.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/0.7-show-account.md, docs/MatrixOne/Reference/System-tables.md
=> update load-data/load-s3/basic-sql/show-account docs

docs/MatrixOne/Develop/import-data/bulk-load/0.7-load-csv.md, docs/MatrixOne/Develop/import-data/bulk-load/0.7-load-jsonline.md, docs/MatrixOne/Develop/import-data/bulk-load/0.7-load-s3.md
=> update parallel load command

docs/MatrixOne/Develop/Transactions/common-transaction-overview.md, docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/snapshot-isolation.md
=> update Snapshot Isolation docs

docs/MatrixOne/FAQs/deployment-faqs.md
issue #
https://github.com/matrixorigin/matrixorigin.io/issues/293
=> update docs in io issue 293

.github/workflows/test_ci.yml
=> chore(ci): add test_cn img

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table.md
=> add cluster by statement when create table

mkdocs.yml
调整 0.3.0 多版本语言切换功能
issue #
https://github.com/matrixorigin/mo-website/issues/90
=> feat(domain): update 0.3.0 domain language

mkdocs.yml
=> Feat domian lang 0.5.0

mkdocs.yml
=> feat(domain): update 0.6.0 domain language

mkdocs.yml
调整多版本语言切换功能
https://github.com/matrixorigin/mo-website/issues/90
issue #
=> feat(domain): update domain language

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
=> add content of SET parameter in LOAD DATA

docs/MatrixOne/Reference/System-Parameters/configuration-settings.md
=> modify the doc of config_settings

docs/MatrixOne/Reference/Builtin-Functions/Mathematical/power.md
https://github.com/matrixorigin/matrixorigin.io.cn/issues/267
issue #
=> update docs in issue #267

mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/265
https://github.com/matrixorigin/matrixorigin.io.cn/issues/266
=> update docs in issue #265#266

docs/MatrixOne/Test/performance-testing/TPCC-test-with-matrixone.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/277
=> update docs in io.cn issue #277

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/278
https://github.com/matrixorigin/matrixorigin.io.cn/issues/279
=> update docs in io.cn issue #278/279

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/how-to-use.md, docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/implicit-transaction.md, docs/MatrixOne/Reference/Data-Types/0.8-data-types.md, docs/MatrixOne/Reference/Data-Types/data-types.md, docs/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/sleep.md, docs/MatrixOne/Reference/SQL-Reference/Data-Control-Language/alter-account.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table.md, docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md, docs/MatrixOne/Test/performance-testing/SSB-test-with-matrixone.md, docs/MatrixOne/Test/performance-testing/TPCH-test-with-matrixone.md, docs/MatrixOne/Troubleshooting/query-table-statistics.md
=> fix the format error of comment

docs/MatrixOne/Develop/connect-mo/connect-to-matrixone-with-go.md, docs/MatrixOne/Develop/connect-mo/python-connect-to-matrixone.md, docs/MatrixOne/Tutorial/develop-golang-crud-demo.md
=> add golong connect mo docs

docs/MatrixOne/Overview/matrixone-architecture-design.md, docs/MatrixOne/Reference/System-tables.md, docs/MatrixOne/Tutorial/springboot-hibernate-crud-demo.md, docs/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md
=> fix the version number

docs/MatrixOne/Develop/connect-mo/0.8-database-client-tools.md
issue #
https://github.com/matrixorigin/matrixone/issues/6367
=>  no need to change the navicat version

docs/MatrixOne/Reference/Variable/system-variables/save_query_result.md
=> add save query result doc

docs/MatrixOne/Reference/0.8-System-tables.md
issue #
https://github.com/matrixorigin/matrixone/issues/7877
=> add rows of sql execution results to statement_info

docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md
…know why.this PR add a tip for this.
issue #8522
https://github.com/matrixorigin/matrixone/issues/8522
Launc panic after changing branch build,It makes confused and don't know why.this PR add a tip for this.
=> Launch panic after changing branch, build,add a tip for this.

docs/MatrixOne/Reference/System-tables.md
=> fix description error

docs/MatrixOne/Overview/mysql-compatibility.md
=> modify mysql compatibility:add content of "not support escaped by"

docs/MatrixOne/Develop/import-data/bulk-load/0.8-load-s3.md
issue #
https://github.com/matrixorigin/matrixone/issues/8113
=> Added security guarantee for s3 authentication information

docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/0.8-show-function-status.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/0.8-show-grants.md
issue #
https://github.com/matrixorigin/matrixone/issues/6632
=> add docs of show statement #6632

docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/kill.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/298
=> update docs in issue #298

docs/MatrixOne/Reference/Data-Types/0.8-enum-type.md
issue #
https://github.com/matrixorigin/matrixone/issues/6613
=> add docs of enum type

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/operators/cast-functions-and-operators/0.8-cast.md
issue #
https://github.com/matrixorigin/matrixone/issues/6616
=> Type conversion from time types to int

docs/MatrixOne/Reference/System-tables.md
=> fix the description of datalength in system table 

docs/MatrixOne/Develop/export-data/modump.md
=> fix description of exporting content

docs/MatrixOne/Develop/export-data/0.8-modump.md
issue #
https://github.com/matrixorigin/MO-Cloud/issues/402
=> New parameters are added to mo-dump

docs/MatrixOne/Reference/0.8-System-tables.md
issue #
https://github.com/matrixorigin/matrixone/issues/7555
=> Add metadata tables and views

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/0.8-insert-on-duplicate.md
issue #
https://github.com/matrixorigin/matrixone/issues/6567
=> add the doc of insert on duplicate key

docs/MatrixOne/Deploy/MatrixOne-Operator-mgmt.md, docs/MatrixOne/Deploy/MatrixOne-cluster-Scale.md, docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md, docs/MatrixOne/Deploy/update-MatrixOne-cluster.md, mkdocs.yml
=> update the docs of deploy mo cluster

docs/MatrixOne/Reference/System-tables.md
=> modify system tables

docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/join/join.md
=> fix the Syntax rendering error

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/information-functions/current_role.md, docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/information-functions/current_user.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-roles.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixone/issues/7888
=> add the docs of show roles

docs/MatrixOne/Deploy/MatrixOne-start-stop.md
=> add doc of mo-cluster stop-start

docs/MatrixOne/Deploy/MatrixOne-Operator-mgmt.md, docs/MatrixOne/Deploy/MatrixOne-cluster-Scale.md, docs/MatrixOne/Tutorial/springboot-hibernate-crud-demo.md, docs/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md
issue #
https://github.com/matrixorigin/matrixorigin.io/issues/357
=> fix the error of local path

docs/MatrixOne/Reference/Variable/custom-variable.md
=> modify the doc of custom variable

docs/MatrixOne/Reference/SQL-Reference/Data-Control-Language/alter-user.md, docs/MatrixOne/Reference/SQL-Reference/Other/Set/set-role.md, docs/MatrixOne/Security/how-tos/user-guide.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixone/issues/6682
=> add doc of alter user

docs/MatrixOne/Deploy/import-data-from-minio-to-mo.md
=> add doc of import data from minio to mo

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
issue #
https://github.com/matrixorigin/matrixone/issues/8142
=> remove the constraints of parallel load local file

docs/MatrixOne/Develop/Publish-Subscribe/pub-sub-overview.md
=> add doc of pub-sub overview

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/alter-publication.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-publication.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-subscription.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/drop-publication.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-create-publication.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-publications.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-subscriptions.md
=> add the docs of pub-sub sql statments

docs/MatrixOne/Deploy/MatrixOne-Operator-mgmt.md, docs/MatrixOne/Deploy/MatrixOne-cluster-Scale.md, docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md, docs/MatrixOne/Deploy/health-check-resource-monitoring.md, docs/MatrixOne/Deploy/update-MatrixOne-cluster.md
=> modify the docs of deploying mo cluster

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/parser_camp_event.md
issue #
https://github.com/matrixorigin/matrixone/issues/4532
=> modify the version number of GO

docs/MatrixOne/Test/testing-tool/mo-tester.md
=> modify the Title level

docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md
issue #
https://github.com/matrixorigin/matrixone/issues/4532
=> remove the constraint of ARM framework

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-publication.md
=> modify the syntax of create publication

docs/README.md
=> optimize the description

docs/MatrixOne/Deploy/mgmt-cn-group-using-proxy.md
=> add new doc of manage cn with proxy

docs/MatrixOne/Overview/feature/cost-effective.md
=> new doc of key feature

docs/MatrixOne/Overview/architecture/architecture-cold-hot-data-separation.md, docs/MatrixOne/Overview/architecture/architecture-logservice.md, docs/MatrixOne/Overview/architecture/architecture-proxy.md
=> add new docs of architecture details

docs/MatrixOne/Overview/feature/matrixone-feature-list.md, docs/MatrixOne/Overview/feature/mysql-compatibility.md, docs/MatrixOne/Reference/Data-Types/data-types.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/369
=> Offline enum related documents

docs/MatrixOne/Reference/Functions-and-Operators/String/substring.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/366
https://github.com/matrixorigin/matrixorigin.io.cn/issues/367
=> deleteconstraints and modify the example of substring

docs/MatrixOne/Reference/Functions-and-Operators/String/split_part.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/364
=> add new doc of split-part

docs/MatrixOne/Reference/SQL-Reference/Data-Control-Language/create-account.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/381
=> delete the open Parameter of create account

docs/MatrixOne/Reference/Functions-and-Operators/Mathematical/rand.md
=> add new doc of rand

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table.md
=> modify the doc of partition syntax

docs/MatrixOne/Develop/import-data/bulk-load/using-source.md
=> modify the command of source

docs/README.md
=> Improve wording and some links of Readme

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method3.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/412
=> add content of mainland image

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md
=> add content of binary for arm system

docs/MatrixOne/Develop/develop-overview.md, mkdocs.yml
=> add new doc of develop overview

docs/MatrixOne/Develop/schema-design/create-view.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/384
=> new doc of create view overview

docs/MatrixOne/Overview/matrixone-introduction.md
=> Update image link

mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/430
https://github.com/matrixorigin/matrixorigin.io.cn/issues/429
=> Chapter off line

docs/MatrixOne/Develop/import-data/bulk-load/load-csv.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/423
=> delete the duplicate descriptions

docs/MatrixOne/Reference/Functions-and-Operators/Json/json-functions.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/425
=> fix the misspelling

mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/439
=> feature overview offline

docs/MatrixOne/Overview/feature/mysql-compatibility.md, docs/MatrixOne/Overview/matrixone-feature-list.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/404
=> refresh feature-list and compatibility

docs/MatrixOne/Overview/feature/mysql-compatibility.md, docs/MatrixOne/Overview/matrixone-feature-list.md, docs/MatrixOne/Reference/Limitations/mo-partition-support.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/426
=> modify the description of partition

docs/MatrixOne/FAQs/deployment-faqs.md, docs/MatrixOne/Get-Started/install-standalone-matrixone.md, docs/MatrixOne/Overview/matrixone-introduction.md
issue #388, #427 
Update OS/hardware for new version
=> Install requirement update

docs/MatrixOne/Reference/Variable/system-variables/sql-mode.md
=> fix the theme error of sql mode

docs/MatrixOne/Overview/feature/mysql-compatibility.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/456
=> mo dose not support mediumint

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/460
=> fix the error of installpackage

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/explicit-transaction.md
=> fix the description error

docs/MatrixOne/Get-Started/basic-sql.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/489
=> fix the wrongly written

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/499
=> delete clang from linux env

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/insert-on-duplicate.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/498
=> fix the content of conflict description

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/503
=> fix the deadlink of installation

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method3.md, docs/MatrixOne/Maintain/mount-data-by-docker.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/518
=> launch mo by docker add param --privileged=true

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/546
=> mkdir plus -p

docs/MatrixOne/Develop/Publish-Subscribe/multi-account-overview.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/453
=> add multi-account-overview

docs/MatrixOne/Reference/Operators/operators/comparison-functions-and-operators/not-equal.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/552
=> fix the untranslated error

docs/MatrixOne/Tutorial/develop-golang-crud-demo.md
issue #507 
@lacrimosaprinz Please synchronize english version.
=> Fix golang demo error

docs/MatrixOne/Maintain/mo_ctl.md
issue #551 
@lacrimosaprinz Please synchronize english version.
=> Update mo_ctl reference

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/592
=> fix the load csv link error

docs/MatrixOne/Reference/SQL-Reference/Other/Explain/explain-workflow.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-index.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/598
https://github.com/matrixorigin/matrixorigin.io.cn/issues/600
=> translate en to chinese

docs/javascripts/extra.js, mkdocs.yml
=> feat(tongji): baidu tongji

docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/select.md
issue #
https://github.com/matrixorigin/matrixone/issues/10356
=> support group by alias

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/616
=> fix the error of setting mo-ctl

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
=> add the limitation of field

docs/MatrixOne/Reference/1.0-System-tables.md, docs/MatrixOne/Reference/SQL-Reference/Data-Control-Language/1.0-alter-account.md
issue #
https://github.com/matrixorigin/matrixone/issues/8937
=> new content of restricted

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/631
=> modify content of minio commands

mkdocs.yml
=> Update mkdocs.yml for 0.8

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/explicit-transaction.md, docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/implicit-transaction.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/611
=> modify the content of implicat and explicit transaction

docs/MatrixOne/Reference/System-tables.md
=> modify the field of mo-udf-table

docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-processlist.md
issue #
https://github.com/matrixorigin/matrixone/issues/10359
=> add more details of processlist

docs/MatrixOne/Overview/matrixone-feature-list.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/alter-table.md
issue #
https://github.com/matrixorigin/matrixone/issues/10380
=> new content of alter table

docs/MatrixOne/Develop/schema-design/data-integrity/auto-increment-integrity.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table.md
issue #
https://github.com/matrixorigin/matrixone/issues/6598
=> support set auto-increment=n

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
=> fix: bracket mismatch and typo

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/replace.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixone/issues/6572
=> new docs of replace

docs/MatrixOne/Test/performance-testing/TPCH-test-with-matrixone.md
=> support tpch composite primary

docs/MatrixOne/Reference/System-tables.md
https://github.com/matrixorigin/matrixone/pull/10330
issue #
https://github.com/matrixorigin/matrixone/issues/10281
=> update the content of system table

docs/MatrixOne/Reference/Operators/operators/operators.md
=> fix the broken link in operator

docs/MatrixOne/Reference/Data-Types/data-types.md, docs/MatrixOne/Reference/Data-Types/enum-type.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixone/issues/6613
=> doc of enum

docs/MatrixOne/Reference/Operators/operators/comparison-functions-and-operators/comparison-functions-and-operators-overview.md, docs/MatrixOne/Reference/Operators/operators/comparison-functions-and-operators/ilike.md, docs/MatrixOne/Reference/Operators/operators/comparison-functions-and-operators/like.md, docs/MatrixOne/Reference/Operators/operators/operators.md, mkdocs.yml
=> add doc of ilike

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/alter-stage.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-stage.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/drop-stage.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-roles.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-stage.md, docs/MatrixOne/Reference/System-tables.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixone/issues/8544
=> new docs of stage

docs/MatrixOne/Develop/schema-design/data-integrity/foreign-key-constraints.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table.md
issue #
https://github.com/matrixorigin/matrixone/issues/6597
=> support foreign key

docs/MatrixOne/Develop/import-data/insert-data.md
=> remove constraints from insert data

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/alter-table.md
=> temporary table and cluster table do not suppurt alter table

docs/MatrixOne/FAQs/deployment-faqs.md, docs/MatrixOne/Maintain/backup-restore/modump-backup-restore.md, docs/MatrixOne/Reference/Functions-and-Operators/Datetime/to-seconds.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-roles.md, docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md, docs/MatrixOne/Reference/Variable/system-variables/save_query_result.md, mkdocs.yml
=> fix the broken links and index error

docs/MatrixOne/Develop/connect-mo/connect-to-matrixone-with-go.md, docs/MatrixOne/Tutorial/gorm-golang-crud-demo.md, mkdocs.yml
issue #
补充golang的ORM工具gorm以连接和操作(CRUD)MO
=> add a Tutorial:gorm-golang-crud-demo

docs/MatrixOne/Develop/read-data/subquery.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/693
=> fix the theme error #693

docs/MatrixOne/Develop/export-data/modump.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/692
=> fix the error of csv example in modump doc

docs/MatrixOne/Develop/read-data/cte.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/694
=> enhancement the cte doc

docs/MatrixOne/Overview/architecture/matrixone-architecture-design.md, docs/MatrixOne/Overview/architecture/streaming.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/678
https://github.com/matrixorigin/matrixorigin.io.cn/issues/677
=> overview of stream engine

docs/MatrixOne/Develop/schema-design/create-secondary-index.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/688
=> add constraint of sec index

docs/MatrixOne/Get-Started/basic-sql.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/682
=> add replace into the doc of basic sql

docs/MatrixOne/Overview/matrixone-feature-list.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/676
=> modify feature list doc

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md, docs/MatrixOne/Maintain/mo_ctl.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/705
=> modify the path of launch

docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/how-to-use.md, docs/MatrixOne/Reference/System-Parameters/distributed-configuration-settings.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/684
=> 1.0 switch transaction mode

docs/MatrixOne/Overview/matrixone-feature-list.md
=> enhancement the heading name

docs/MatrixOne/Develop/import-data/bulk-load/using-source.md, docs/MatrixOne/Migrate/migrate-from-mysql-to-matrixone.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/690
https://github.com/matrixorigin/matrixorigin.io.cn/issues/689
=> add constraints of migration from mysql to mo

docs/MatrixOne/Overview/feature/mysql-compatibility.md
=> modify the compatibility

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/718
=> modify the version number of mo operator

mkdocs.yml
issue #729
Allow the user to copy a code block's contents to the clipboard.
=> fix(code-fence): enable code copy button

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/732
=> highlight recommended docker as container engine

docs/MatrixOne/Overview/architecture/architecture-tae.md, docs/MatrixOne/Overview/architecture/streaming.md
=> update the path of images

docs/javascripts/extra.js
=> fix(tongji): update tongji code

docs/MatrixOne/Reference/System-tables.md
issue #
https://github.com/matrixorigin/matrixone/issues/11583
=> Support statistics view in information_schema

docs/MatrixOne/Reference/System-tables.md
issue #
https://github.com/matrixorigin/matrixone/issues/11502
Only adjust 1.1 version
=> 1.1 version add sql hotspot

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/1.1-load-data.md
issue #
https://github.com/matrixorigin/matrixone/issues/9955
=> add content of load data inline

docs/MatrixOne/Overview/feature/key-feature-multi-accounts.md
issue #672
Fixed the image displaying problem in the Multi-Account doc.
=> fix: adjusted img size

docs/MatrixOne/Develop/Transactions/common-transaction-overview.md, docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/isolation-level.md
=> fix error of texting

docs/MatrixOne/Reference/Functions-and-Operators/1.1-Vector/cosine_similarity.md, docs/MatrixOne/Reference/Functions-and-Operators/1.1-Vector/inner_product.md, docs/MatrixOne/Reference/Functions-and-Operators/1.1-Vector/l1_norm.md, docs/MatrixOne/Reference/Functions-and-Operators/1.1-Vector/l2_norm.md
=> update the link of pics

docs/MatrixOne/Develop/Ecological-Tools/BI-Connection/Superset-connection.md, docs/MatrixOne/parser_camp_event.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/764
=> fix Displaying error 764

docs/MatrixOne/Reference/Variable/system-variables/system-variables-overview.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/753
=> fix Enhancement error 753

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/1.1-alter-sequence.md
=> modify the example of alter sequence

docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/Flink.md, docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/Spark.md, mkdocs.yml
=> new doc of flink and spark

docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/Spark.md
=> error MatrixOne install link

mkdocs.yml
issue #
Recovered the `"edit this page"` button.
=> feat(content): added "edit this page" btn

docs/MatrixOne/Performance-Tuning/optimization-concepts/1.1-through-partition-pruning.md
=> doc of partition pruning

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/1.1-create-stage.md
issue #
https://github.com/matrixorigin/matrixone/issues/11385
=> Support more s3option for stage

docs/MatrixOne/Overview/architecture/architecture-logtail.md, docs/MatrixOne/Overview/architecture/architecture-transaction-lock.md, mkdocs.yml
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/786
=> architechture doc of logtail and lock

docs/MatrixOne/Reference/1.1-System-tables.md
issue #
https://github.com/matrixorigin/matrixone/issues/11321
=> add mo_transactions into sys-tab

docs/MatrixOne/Reference/SQL-Reference/SQL-Type.md, mkdocs.yml
=>  sql type doc

docs/MatrixOne/Test/performance-testing/SSB-test-with-matrixone.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/793
=> group by support alias name

docs/MatrixOne/Reference/Language-Structure/comment.md
issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/791
=> modify the doc of comment

docs/MatrixOne/Overview/1.1-matrixone-feature-list.md, docs/MatrixOne/Overview/feature/1.1-mysql-compatibility.md, docs/MatrixOne/Reference/Limitations/1.1-mo-partition-support.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/1.1-create-table.md
=> support rang list partition

docs/MatrixOne/Release-Notes/v1.0.0-rc2.md
=> modify doc of rc-2 releasenote

docs/MatrixOne/FAQs/sql-faqs.md
=> Fix SQL FAQs lint errors

.gitignore, docs/MatrixOne/Security/TLS-introduction.md
=> fix typo：PREFERED写错了，应该是PREFERRED 

.github/workflows/lint.yml
issue #
set `fetch-depth` & `since_last_remote_commit`
=> ci: update lint settings in workflow

mkdocs.yml
issue #
参考手册>函数to_seconds()和to_days()连接反了，进行调整。
=> fix mkdocs link typo

.github/workflows/lint.yml
=> use github api instead local git

docs/MatrixOne/Reference/Language-Structure/keywords.md
=> main-fix-keywords:del % prec XXXXX

docs/MatrixOne/Reference/Data-Types/enum-type.md
=> Remove enum limit of filtering and sorting

docs/MatrixOne/Overview/matrixone-feature-list.md
=> Update 1.1 feature list

docs/MatrixOne/Overview/matrixone-function-list.md, docs/MatrixOne/Reference/Functions-and-Operators/matrixone-function-list.md, mkdocs.yml
=> add doc of matrixone-function-list

docs/MatrixOne/Reference/Functions-and-Operators/matrixone-function-list.md
=> update matrixone-function-list for 1.0.2

docs/MatrixOne/Reference/Functions-and-Operators/matrixone-function-list.md, mkdocs.yml
=> add doc of  matrixone-function-list for main

docs/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md, docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md, docs/MatrixOne/Deploy/update-MatrixOne-cluster.md, docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/DataX-write.md, docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/Flink.md, docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/Spark.md, docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/seatunnel-write.md, docs/MatrixOne/Develop/connect-mo/configure-mo-ssl-connection.md, docs/MatrixOne/Develop/connect-mo/database-client-tools.md, docs/MatrixOne/Develop/connect-mo/python-connect-to-matrixone.md, docs/MatrixOne/Develop/import-data/bulk-load/load-csv.md, docs/MatrixOne/Develop/import-data/bulk-load/using-source.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method3.md, docs/MatrixOne/Maintain/mo_ctl.md, docs/MatrixOne/Maintain/mount-data-by-docker.md, docs/MatrixOne/Migrate/migrate-from-mysql-to-matrixone.md, docs/MatrixOne/Overview/feature/feature-overview.md, docs/MatrixOne/Security/TLS-introduction.md
=> Change the installation package version to 1.1.0

docs/MatrixOne/Overview/matrixone-feature-list.md
=> Add function list to feature list

docs/MatrixOne/Reference/System-tables.md
=> update doc of System_tables

docs/MatrixOne/Develop/export-data/modump.md, docs/MatrixOne/Maintain/backup-restore/modump-backup-restore.md
=> update mo-dump link

docs/MatrixOne/Develop/udf/udf-python-advanced.md
=> add a ML demo

docs/MatrixOne/Overview/matrixone-feature-list.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-function-python.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-function-sql.md, docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/drop-function.md, docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-function-status.md, mkdocs.yml
=> add udf sql_reference

docs/MatrixOne/Reference/Functions-and-Operators/Aggregate-Functions/var_pop.md, docs/MatrixOne/Reference/Functions-and-Operators/matrixone-function-list.md, mkdocs.yml
=> add function var_pop

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-cluster-table.md, mkdocs.yml
=> add create-cluster-table

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/insert-on-duplicate-ignore.md, mkdocs.yml
=> add insert-on-duplicate-ignore

docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md, docs/MatrixOne/Maintain/mo_ctl.md, docs/MatrixOne/Test/performance-testing/SSB-test-with-matrixone.md, docs/MatrixOne/Test/performance-testing/TPCC-test-with-matrixone.md, docs/MatrixOne/Test/performance-testing/TPCH-test-with-matrixone.md, docs/MatrixOne/Test/testing-tool/mo-tester.md
=> add GitHub image address

docs/MatrixOne/Tutorial/django-python-crud-demo.md, mkdocs.yml
=> add django-python-crud-demo

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
issue [#275](https://github.com/matrixone-cloud/moc-docs/issues/275)
=> compressed file format for load data

docs/MatrixOne/Reference/Variable/system-variables/timezone.md
=> change mysql->mo

docs/MatrixOne/Develop/read-data/window-function/window-function.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md, docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2.md, docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method3.md
=> update standalone install

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
issue #[2604](https://github.com/matrixorigin/MO-Cloud/issues/2604)
=> add parameters to load data

docs/MatrixOne/Reference/Functions-and-Operators/Aggregate-Functions/count.md, docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/select.md
=> add dof of distinct

docs/MatrixOne/Develop/connect-mo/connect-to-matrixone-with-c#.md, docs/MatrixOne/Tutorial/c-net-crud-demo.md, mkdocs.yml
=> add doc of c# connect mo

docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md
=> [1.1] update lower_case_table_names

docs/MatrixOne/Reference/Data-Types/data-types.md
=> add bit data type

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/create-table-as-select.md, mkdocs.yml
issue [#10362](https://github.com/matrixorigin/matrixone/issues/10362)
=> add doc of ctas

docs/MatrixOne/Develop/schema-design/data-integrity/foreign-key-constraints.md, docs/MatrixOne/Reference/Variable/system-variables/foreign_key_checks.md, mkdocs.yml
=> Foreign key checks

docs/MatrixOne/Overview/matrixone-vs-other_databases/matrixone-positioning.md, mkdocs.yml
=> add doc of matrixone-positioning

docs/MatrixOne/Overview/matrixone-vs-other_databases/matrixone-vs-oltp.md, mkdocs.yml
=> add doc of matrixone-vs-oltp

docs/MatrixOne/Develop/schema-design/create-table-as-select.md, mkdocs.yml
=> add doc of schema-design_ctas

docs/MatrixOne/Overview/architecture/architecture-matrixone-operator.md, mkdocs.yml
=> add doc of architecture-matrixone-operator

docs/MatrixOne/Deploy/deploy-Matrixone-cluster/deploy-MatrixOne-cluster-with-k8.md, docs/MatrixOne/Deploy/deploy-Matrixone-cluster/deploy-MatrixOne-cluster-without-k8.md, mkdocs.yml
=> add doc of deploy-MatrixOne-cluster-with-k8

docs/MatrixOne/Tutorial/rag-demo.md, mkdocs.yml
=> add doc of rag-demo

docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data.md
=> uodate doc of load data

docs/MatrixOne/Reference/Variable/system-variables/keep_user_target_list_in_result.md
=> update keep_user_target_list_in_result default 1

.github/workflows/cd.yml, .github/workflows/pre-cd.yml
=> optimize image build ci

docs/MatrixOne/FAQs/deployment-faqs.md, docs/MatrixOne/Get-Started/install-standalone-matrixone.md
=> update support os

docs/MatrixOne/Reference/Variable/system-variables/save_query_result.md
=> Setting parameters in the configuration file is not supported

docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/join/cross-join.md, docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/join/join.md, mkdocs.yml
=> add doc of Cross join

docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/select.md
=> add explanation to select xx from dual

mkdocs.yml
=> fix load data link

docs/MatrixOne/Tutorial/htap-demo.md, mkdocs.yml
=> add doc of htap application development example

docs/MatrixOne/Deploy/deploy-matrixone-single-with-s3.md, mkdocs.yml
issue #[587](https://github.com/matrixorigin/matrixorigin.io/issues/587)
=> add doc of deploy-matrixone-single-with-s3

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/rename-table.md, mkdocs.yml
=> add doc of rename

docs/MatrixOne/Tutorial/search-picture-demo.md
=> add doc of search-pic

docs/MatrixOne/Reference/Functions-and-Operators/Other/load_file.md
=> add limit tto load_file

docs/MatrixOne/Reference/Variable/system-variables/illegal_login_restrictions.md, docs/MatrixOne/Reference/Variable/system-variables/password_complex.md, docs/MatrixOne/Reference/Variable/system-variables/whitelist.md, mkdocs.yml
=> add doc of Password complexity and lifecycle management

mkdocs.yml
=> docs(moi): moc => moi

docs/MatrixOne/Develop/Vector/vector_index.md
=> fix vec index

docs/MatrixOne/Reference/System-tables.md
=> update system tables

.github/workflows/lint.yml
=> fix(lint): cannot find matching key
