.github/workflows/cd.yml

增加 mike cd 脚本, 支持 3 种功能
1. 更新 main 内容到 dev 版本
2. 更新指定旧版本内容
3. 根据最新 main 内容发布全新版本
目前约定 cd 脚本都是用 main 分支上的, 忽略其余分支 workflow

feat: add mike cd

---

docs/MatrixOne/Get-Started/install-standalone-matrixone.md

We should enter the directory first then checkout to the stable version.
issue #
We should enter the directory first then checkout to the stable version.

docs: fix order when get stable version to build

---

.github/workflows/cd.yml
.github/workflows/pre-cd.yml
.github/workflows/test_ci.yml
Dockerfile
mkdocs.yml
requirements.txt

issue #641
Update `mkdocs-material` to `9.1.21`:
- To support site search with Chinese content
- <img width="480" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/86586270/9dd5d014-d582-4542-95f2-c6bc6ab3496a">
-  Customize the separator for indexing and query tokenization:
- Before:
- After:
- Update the version of python to `3.10` in CI

build(mkdocs): bump `mkdocs-material` to `9.1.21`

---

docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md

issue #742
fix the bin package name from “mo-v1.0.0-rc1-linux-amd64.zip” to "mo-v1.0.0-rc1-linux-x86_64.zip"

fix MO bin package name (amd -> x86_64) in download link

---

docs/MatrixOne/Develop/connect-mo/database-client-tools.md

issue #727 
过时的启动方法 “./mo-service ”需要删除或者更改为mo_ctl方式
在database-client-tools.md中已经在文章最开始统一说明了需要启动mo，后续无需再启动，故直接删除。

delete "./mo-service" start method

---

docs/MatrixOne/Maintain/mount-data-by-docker.md

mod doc docker mount data&config

---

docs/MatrixOne/Develop/Ecological-Tools/BI-Connection/FineBI-connection.md
docs/MatrixOne/Develop/Ecological-Tools/BI-Connection/Superset-connection.md
docs/MatrixOne/Develop/Ecological-Tools/BI-Connection/yonghong-connection.md
docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/DataX-write.md
docs/MatrixOne/Develop/Ecological-Tools/Computing-Engine/seatunnel-write.md
docs/MatrixOne/Develop/Transactions/matrixone-transaction-overview/how-to-use.md
mkdocs.yml

add new xiantianneng-docs

---

docs/MatrixOne/Develop/Ecological-Tools/Scheduling-Tools/dolphinScheduler.md
mkdocs.yml

new doc of dolphinscheduling

---

docs/MatrixOne/Develop/import-data/bulk-load/1.1-load-s3.md

support use arn to load data

---

docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/1.1-create-index.md

support secondary index

---

docs/MatrixOne/FAQs/sql-faqs.md

Update SQL FAQs

---

docs/MatrixOne/FAQs/sql-faqs.md
docs/MatrixOne/Maintain/mo_ctl.md

issue :
https://github.com/matrixorigin/mo_ctl_standalone/issues/45
mo_ctl can‘t set path containing "${MO_PATH}",users need to use '\${MO_PATH}' .

add a note to mo_ctl doc

---

mkdocs.yml

https://github.com/matrixorigin/mo-website/issues/438
Added the link of MatrixOne Cloud docs to the navigation tabs.

feat(navigation): added `moc-docs` link to the navigation tabs

---

CONTRIBUTING.md

issue #
Updated the `CONTRIBUTING.md`.

chore: updated `CONTRIBUTING.md`

---

docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md

case Sensitity

---

docs/MatrixOne/Reference/Variable/system-variables/sql-mode.md

uopdate sql_mode

---

docs/MatrixOne/Develop/distinct-data/bitmap.md
docs/MatrixOne/Develop/distinct-data/count-distinct.md
docs/MatrixOne/Reference/Functions-and-Operators/Aggregate-Functions/bitmap.md
docs/MatrixOne/Reference/Functions-and-Operators/matrixone-function-list.md
mkdocs.yml

add doc of bitmap

---

docs/MatrixOne/Overview/matrixone-vs-other_databases/matrixone-positioning.md
mkdocs.yml

add doc of matrixone-positioning

---

docs/MatrixOne/Reference/Operators/operators/logical-operators/not.md

issue #[2087](https://github.com/matrixorigin/MO-Cloud/issues/2087)

update doc of not|!

---

docs/MatrixOne/Reference/Variable/system-variables/keep_user_target_list_in_result.md
mkdocs.yml

add doc of keep_user_target_list_in_result

---

docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md

update doc of lower_case_tables_name

---

docs/MatrixOne/Reference/SQL-Reference/Other/Explain/explain-prepared.md
mkdocs.yml

add doc of explain prepared

---

docs/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md
docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md
docs/MatrixOne/Reference/mo-tools/mo_ctl.md
docs/MatrixOne/parser_camp_event.md

update go version from 1.20 to 1.22.3

---

docs/MatrixOne/FAQs/sql-faqs.md

issue #[3822](https://github.com/matrixorigin/MO-Cloud/issues/3822)

Table Compression Ratio Query Description

---

docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md

issue #[3844](https://github.com/matrixorigin/MO-Cloud/issues/3844)

lower_Case_tables_name

---

docs/MatrixOne/Develop/udf/udf-python-advanced.md

issue #[17632](https://github.com/matrixorigin/matrixone/issues/17632)

udf --local-infile

---

docs/MatrixOne/Maintain/backup-restore/active-standby.md
docs/MatrixOne/Maintain/cdc/mo-mysql.md
docs/MatrixOne/Maintain/cdc/mocdc.md
mkdocs.yml

add doc of cdc and mo-active-standby

---

docs/MatrixOne/Deploy/deploy-Matrixone-cluster/deploy-MatrixOne-cluster-with-k8.md
docs/MatrixOne/Deploy/deploy-Matrixone-cluster/deploy-MatrixOne-cluster-without-k8.md

 Support changing cacheVolume of cn and dn after mo is deployed

---

docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/apply/cross-apply.md
docs/MatrixOne/Reference/SQL-Reference/Data-Query-Language/apply/outer-apply.md
docs/MatrixOne/Reference/SQL-Reference/SQL-Type.md
mkdocs.yml

add doc of apply

---

docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-account.md

Reverts matrixorigin/matrixorigin.io.cn#1182

Revert "fix"
